# Site settings
title: Rogue Identity
email: admin@rogueidentity.com
description: > # this means to ignore newlines until "baseurl:"
  Rogue Identity is a software consultancy.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://rogueidentity.com" # the base hostname & protocol for your site
twitter_username: rogue_identity
github_username:  rogueidentity

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 4
paginate_path: "blog/page:num"
